apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo1-springboot
  template:
    metadata:
      labels:
        app: demo1-springboot
    spec:
      containers:
        - name: springboot
          image: kshitijadaundkar/eks-jenkins-demo-1:v.0.0.1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: demo1-springboot-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo1-springboot
